name: Build linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    
    runs-on: ubuntu-latest

    steps:

    # Checkout DMA_Framework's revision, which is pushed
    - name: Checkout of the DMA_Framework
      uses: actions/checkout@v2
      with:
        repository: svlad-90/DMA_Framework
        path: ./
        ref: ${{ github.ref }}
        
    # Create build directory
    - name: Creation of the "../build" directory
      run: mkdir ../build
      shell: bash
      working-directory: ./

    # CMake execution
    - name: CMake
      run: cmake ../DLT-Message-Analyzer
      shell: bash
      working-directory: ../build
    
    # Build of the project
    - name: Make
      run: make -j8
      shell: bash
      working-directory: ../build

    # Unit-tests execution
    - name: unit-tests
      run: make -j8 --target test
      shell: bash
      working-directory: ../build